name: govalidate

on:
  workflow_dispatch:
    inputs:
      warnings:
        description: print warnings as well as errors
        type: boolean
        required: true
        default: false

jobs:
  govalidate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "stable"
      - name: run validator
        run: |
          cd tools
          go run ./govalidate --with-warnings=${{ inputs.warnings }} ../public_suffix_list.dat
